# Generated by Django 4.2.4 on 2023-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='name of user')),
                ('surname', models.CharField(blank=True, max_length=500, null=True, verbose_name='user surname')),
                ('username', models.CharField(max_length=500, verbose_name='username of user')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
